export const states = [
  { name: "Abia", code: "ABA" },
  { name: "Adamawa", code: "YOL" },
  { name: "Akwa Ibom", code: "UYO" },
  { name: "Anambra", code: "AWK" },
  { name: "Bauchi", code: "BAU" },
  { name: "Bayelsa", code: "YEN" },
  { name: "Benue", code: "MKD" },
  { name: "Borno", code: "MAI" },
  { name: "Cross River", code: "CAL" },
  { name: "Delta", code: "ASB" },
  { name: "Ebonyi", code: "EBS" },
  { name: "Edo", code: "BEN" },
  { name: "Ekiti", code: "ADO" },
  { name: "Enugu", code: "ENS" },
  { name: "Gombe", code: "GOM" },
  { name: "Imo", code: "OWE" },
  { name: "Jigawa", code: "DUT" },
  { name: "Kaduna", code: "KAD" },
  { name: "Kano", code: "KAN" },
  { name: "Katsina", code: "KAT" },
  { name: "Kebbi", code: "BIR" },
  { name: "Kogi", code: "LOK" },
  { name: "Kwara", code: "ILR" },
  { name: "Lagos", code: "LOS" },
  { name: "Nasarawa", code: "LAF" },
  { name: "Niger", code: "MIN" },
  { name: "Ogun", code: "ABE" },
  { name: "Ondo", code: "AKR" },
  { name: "Osun", code: "OSH" },
  { name: "Oyo", code: "IBD" },
  { name: "Plateau", code: "JOS" },
  { name: "Rivers", code: "PHC" },
  { name: "Sokoto", code: "SKO" },
  { name: "Taraba", code: "JAL" },
  { name: "Yobe", code: "DAM" },
  { name: "Zamfara", code: "GUS" },
  { name: "Federal Capital Territory", code: "ABJ" },
];
